Update workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -19,6 +19,14 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y php7.4-cli php7.4-xml
 
+    - name: Check .env file
+      run: |
+        cd ./web
+        if [ ! -f .env ]; then
+          echo ".env file not found!"
+          exit 1
+        fi
+
     - name: Install Composer Dependencies
       working-directory: ./web
       run: composer install
